"""Gateway-owned event names for product teaching flows."""

TEACHING_DECISION_EVENT = "teaching.decision"
TEACHING_TURN_COMPLETED_EVENT = "teaching.turn.completed"
CONVERSATION_TURN_COMPLETED_EVENT = "conversation.turn.completed"
QUIZ_EVENT_TYPES = ("quiz.issued", "quiz.scored", "quiz.review_pending")
LEARNER_EVENT_TYPES = ("pedagogy.attempt", "pedagogy.attempt_skipped")
DOCUMENT_EVENT_TYPES = ("document.converted",)
# 消息级操作只记录序号与角色，绝不记录消息正文（见 events.json 的 _privacy）。
MESSAGE_EDIT_EVENT = "message.edited"
MESSAGE_REGENERATE_EVENT = "message.regenerated"
MESSAGE_DELETE_EVENT = "message.deleted"
MESSAGE_EVENT_TYPES = (MESSAGE_EDIT_EVENT, MESSAGE_REGENERATE_EVENT, MESSAGE_DELETE_EVENT)
GATEWAY_EVENT_TYPES = (TEACHING_DECISION_EVENT, TEACHING_TURN_COMPLETED_EVENT, *QUIZ_EVENT_TYPES,
                       CONVERSATION_TURN_COMPLETED_EVENT, *LEARNER_EVENT_TYPES, *DOCUMENT_EVENT_TYPES,
                       *MESSAGE_EVENT_TYPES)

__all__ = ["DOCUMENT_EVENT_TYPES", "GATEWAY_EVENT_TYPES", "LEARNER_EVENT_TYPES", "MESSAGE_DELETE_EVENT",
           "MESSAGE_EDIT_EVENT", "MESSAGE_EVENT_TYPES", "MESSAGE_REGENERATE_EVENT", "QUIZ_EVENT_TYPES",
           "CONVERSATION_TURN_COMPLETED_EVENT", "TEACHING_DECISION_EVENT", "TEACHING_TURN_COMPLETED_EVENT"]
